#!/usr/bin/env python3
"""
Generate Lecture 08 Part1/Part2 markdown in a GitHub-first style.

Constraints enforced by construction:
- Part1: exactly 1 python block (Quickstart) and no other implementation code blocks.
- Part2: 2 python blocks, each preceded by a matching ```math block (Math↔Code 1:1).
- No Zenn-only syntax (:::, @[card], $$).
- time_estimate fixed to "90 minutes" (frontmatter is emitted as-is).
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
ARTICLES = ROOT / "articles"


def write_lines(path: Path, lines: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    text = "\n".join(lines).rstrip() + "\n"
    path.write_text(text, encoding="utf-8")


def mermaid_graphical_model() -> list[str]:
    return [
        "```mermaid",
        "flowchart LR",
        "  subgraph plate[plate i = 1..N]",
        "    z((z_i)) --> x([x_i])",
        "  end",
        "  theta[[θ]] -.-> x",
        "  theta -.-> z",
        "```",
    ]


def mermaid_em_flow() -> list[str]:
    return [
        "```mermaid",
        "flowchart TD",
        "  A[init θ^(0)] --> B[E-step: q(z)=p(z|x,θ^(t))]",
        "  B --> C[M-step: θ^(t+1)=argmax_θ E_q log p(x,z|θ)]",
        "  C --> D{Δlog p(x|θ) small?}",
        "  D -- no --> B",
        "  D -- yes --> E[done]",
        "```",
    ]


def mermaid_elbo_decomp() -> list[str]:
    return [
        "```mermaid",
        "flowchart LR",
        "  L[log p_θ(x)] -->|=| E[ELBO(q,θ)]",
        "  L -->|+| K[KL(q(z)||p_θ(z|x))]",
        "  K -->|≥ 0| T[lower bound gap]",
        "```",
    ]


def mermaid_gmm_components() -> list[str]:
    return [
        "```mermaid",
        "flowchart LR",
        "  X[(x)] --> S{choose k ~ Categorical(π)}",
        "  S --> K1[component 1: N(μ1,Σ1)]",
        "  S --> K2[component 2: N(μ2,Σ2)]",
        "  S --> K3[component K: N(μK,ΣK)]",
        "```",
    ]


def mermaid_lineage() -> list[str]:
    return [
        "```mermaid",
        "flowchart TD",
        "  EM[EM] --> HMM[Baum-Welch (HMM)]",
        "  EM --> FA[Factor Analysis]",
        "  FA --> PPCA[Probabilistic PCA]",
        "  EM --> VEM[Variational EM]",
        "  VEM --> VAE[VAE / amortized inference]",
        "  EM --> EP[Expectation Propagation]",
        "  EM --> MoE[Mixture of Experts]",
        "```",
    ]


def mermaid_log_int_pain() -> list[str]:
    return [
        "```mermaid",
        "flowchart LR",
        "  A[want: max_θ log p_θ(x)] --> B[but: p_θ(x)=∫ p_θ(x,z) dz]",
        "  B --> C[log outside integral: log ∫ ... dz]",
        "  C --> D[no closed form / hard gradients]",
        "  D --> E[introduce q(z) and Jensen]",
        "```",
    ]


def mermaid_numeric_stability() -> list[str]:
    return [
        "```mermaid",
        "flowchart TD",
        "  A[raw density π_k N(x|μ_k,Σ_k)] --> B[underflow to 0]",
        "  B --> C[log space: log π_k + log N]",
        "  C --> D[normalize with log-sum-exp]",
        "  D --> E[exp back to γ]",
        "  E --> F[assert row-sum == 1]",
        "```",
    ]


def mermaid_model_selection() -> list[str]:
    return [
        "```mermaid",
        "flowchart LR",
        "  D[data X] --> F[fit EM for each K]",
        "  F --> L[loglik(K)]",
        "  L --> A[AIC(K)]",
        "  L --> B[BIC(K)]",
        "  A --> S[select K (tradeoff)]",
        "  B --> S",
        "```",
    ]


def mermaid_singularity() -> list[str]:
    return [
        "```mermaid",
        "flowchart TD",
        "  A[component collapses] --> B[Σ_k shrinks]",
        "  B --> C[det(Σ_k) -> 0]",
        "  C --> D[log N(x|μ,Σ) -> +∞ at a point]",
        "  D --> E[loglik spikes, Cholesky fails]",
        "  E --> F[fix: epsI / reinit / priors]",
        "```",
    ]


def frontmatter_part1() -> list[str]:
    return [
        "---",
        'title: "第8回: 潜在変数モデル & EM算法 (Part1: 理論編)"',
        'emoji: "🧩"',
        'type: "tech"',
        'topics: ["機械学習", "数学", "統計学", "Python"]',
        "published: false",
        'slug: "ml-lecture-08-part1"',
        'difficulty: "intermediate"',
        'time_estimate: "90 minutes"',
        'languages: ["Python"]',
        'keywords: ["潜在変数", "EM", "Jensen不等式", "ELBO", "GMM", "責任度"]',
        "---",
        "",
    ]


def frontmatter_part2() -> list[str]:
    return [
        "---",
        'title: "第8回: 潜在変数モデル & EM算法 (Part2: 実装編)"',
        'emoji: "🧩"',
        'type: "tech"',
        'topics: ["機械学習", "数学", "統計学", "Python"]',
        "published: false",
        'slug: "ml-lecture-08-part2"',
        'difficulty: "intermediate"',
        'time_estimate: "90 minutes"',
        'languages: ["Python"]',
        'keywords: ["GMM", "EM", "log-sum-exp", "BIC", "AIC", "初期化"]',
        "---",
        "",
    ]


def author_links_and_license() -> list[str]:
    return [
        "## 著者リンク",
        "- Blog: https://fumishiki.dev",
        "- X: https://x.com/fumishiki",
        "- LinkedIn: https://www.linkedin.com/in/fumitakamurakami",
        "- GitHub: https://github.com/fumishiki",
        "- Hugging Face: https://huggingface.co/fumishiki",
        "",
        "## ライセンス",
        "- CC BY-NC-SA 4.0",
    ]


def build_part1() -> list[str]:
    L: list[str] = []
    L += frontmatter_part1()

    L += [
        "> **この講義について**",
        "> 本講義は「数学基礎編（Course I）」第8回 Part1（理論編）。",
        "> 第7回で出た周辺化 `\\(p(x)=\\int p(x,z)dz\\)` を、Jensen不等式から出発して ELBO に落とし、最後に EM の E/M-step に分解する。",
        ">",
        "> **後編はこちら**: [第8回 Part2（実装編）](/articles/ml-lecture-08-part2)",
        "",
        "## Learning Objectives",
        "",
        "- [ ] 潜在変数モデル `\\(p_\\theta(x)=\\int p_\\theta(x\\mid z)p(z)dz\\)` の難しさを数式で説明できる",
        "- [ ] Jensen 不等式から ELBO を導出できる",
        "- [ ] EM の単調増加（monotonicity）の骨格を示せる",
        "- [ ] GMM の責任度 `\\(\\gamma_{ik}\\)` と更新式を shape つきで説明できる",
        "- [ ] Generalized EM / ECM / label switching / singularity を言語化できる",
        "",
        "---",
        "",
        "## 🚀 Z1. クイックスタート（30秒）",
        "",
        "EM は「直接最大化しにくい周辺尤度 `\\(\\log p_\\theta(x)\\)`」を、下界（ELBO）を介して反復で押し上げる。",
        "",
        "```math",
        "\\log p_\\theta(x) = \\mathrm{ELBO}(q,\\theta) + D_{\\mathrm{KL}}\\bigl(q(z)\\|p_\\theta(z\\mid x)\\bigr)",
        "```",
        "",
        "```python",
        "import numpy as np",
        "",
        "# 1D 2-component GMM EM (minimal quickstart)",
        "np.random.seed(0)",
        "N = 400",
        "x = np.concatenate([",
        "    np.random.normal(-2.0, 0.7, N // 2),",
        "    np.random.normal(2.0, 0.7, N // 2),",
        "])",
        "",
        "K = 2",
        "pi = np.array([0.5, 0.5])",
        "mu = np.array([-1.0, 1.0])",
        "var = np.array([1.0, 1.0])",
        "",
        "",
        "def normal_pdf(x, mu, var):",
        "    return (1.0 / np.sqrt(2 * np.pi * var)) * np.exp(-0.5 * (x - mu) ** 2 / var)",
        "",
        "",
        "def loglik(x, pi, mu, var, eps=1e-12):",
        "    p = sum(pi[k] * normal_pdf(x, mu[k], var[k]) for k in range(K))",
        "    return float(np.sum(np.log(p + eps)))",
        "",
        "",
        "for t in range(6):",
        "    # E-step: responsibilities",
        "    r = np.stack([pi[k] * normal_pdf(x, mu[k], var[k]) for k in range(K)], axis=1)",
        "    r = r / r.sum(axis=1, keepdims=True)",
        "",
        "    # M-step",
        "    Nk = r.sum(axis=0)",
        "    pi = Nk / N",
        "    mu = (r * x[:, None]).sum(axis=0) / Nk",
        "    var = (r * (x[:, None] - mu[None, :]) ** 2).sum(axis=0) / Nk",
        "",
        "    print(\"t=\", t, \"loglik=\", loglik(x, pi, mu, var))",
        "```",
        "",
        "> **Note:** ここでは雰囲気だけ。単調増加がなぜ保証されるかは、この後すべて Jensen から出す。",
        "",
        "---",
        "",
        "## 📖 Z2. チュートリアル（10分）",
        "",
        "この回の5トピックは、すべて同じゴールに収束する。",
        "",
        "| トピック | 一言で言えば | どこで詰まる？ |",
        "|:--|:--|:--|",
        "| 1. 潜在変数モデルの定式化 | `\\(\\int\\)` を抱えた確率モデル | 周辺化で `\\(\\log\\)` の中に積分が入る |",
        "| 2. Jensen→ELBO | `\\(\\log\\int\\)` を下界にする | どこに `\\(q(z)\\)` を挿すのか |",
        "| 3. GMM-EM導出 | 具体例で式が手に取れる | shape を落として破綻 |",
        "| 4. 拡張と幾何 | EM を道具として一般化 | 何を固定して何を最適化？ |",
        "| 5. Boss Battle | Q関数を多変量で展開 | 行列式と二次形式と足し算の順序 |",
        "",
        "まず、潜在変数モデルの痛みを正面から見る。",
        "",
        "---",
        "",
        "## 🌍 Z3. 世界観（20分）",
        "",
        "### 3.1 観測だけで完結しないモデル",
        "",
        "潜在変数モデルの基本形はこれ。",
        "",
        "```math",
        "p_\\theta(x) = \\int p_\\theta(x\\mid z)\\,p(z)\\,dz",
        "```",
        "",
        "観測 `\\(x\\)` だけを見ると複雑だが、潜在 `\\(z\\)` を入れると条件付きで単純になる。",
        "",
        "- 混合分布: `\\(z\\)` が「どの成分から来たか」",
        "- 欠損値: `\\(z\\)` が「観測されていない部分」",
        "- 低次元表現: `\\(z\\)` が「説明変数（潜在空間）」",
        "",
        "ところが MLE をやろうとすると、すぐ壁に当たる。",
        "",
        "```math",
        "\\theta^\\* = \\arg\\max_\\theta \\sum_{i=1}^N \\log p_\\theta(x_i)",
        "\\quad",
        "p_\\theta(x_i)=\\int p_\\theta(x_i,z_i)\\,dz_i",
        "```",
        "",
        "ここで `\\(\\log\\)` と `\\(\\int\\)` の順序が致命的に悪い。",
        "",
        "*mermaid: `\\(\\log\\int\\)` の痛み*",
        "",
        "```mermaid",
        "flowchart LR",
        "  A[want: max_θ log p_θ(x)] --> B[but: p_θ(x)=∫ p_θ(x,z) dz]",
        "  B --> C[log outside integral: log ∫ ... dz]",
        "  C --> D[no closed form / hard gradients]",
        "  D --> E[introduce q(z) and Jensen]",
        "```",
        "",
        "### 3.2 グラフィカルモデルとして眺める",
        "",
        "潜在 `\\(z\\)` は、思考のための可視化でもある。",
        "",
        "*mermaid: 潜在変数モデル（プレート）*",
        "",
    ]
    L += mermaid_graphical_model()
    L += [
        "",
        "この図を見て、次の2点が直感として掴めれば勝ち。",
        "",
        "- 生成方向: `\\(z_i\\to x_i\\)`（潜在が観測を生む）",
        "- 学習方向: `\\(x_i\\)` から `\\(z_i\\)` を推定したくなる（事後推論）",
        "",
        "### 3.3 潜在変数を3つの比喩で捉える",
        "",
        "潜在変数は、同じ記号でも意味が違う。",
        "",
        "1. ラベル（離散）: `\\(z_i\\in\\{1,\\dots,K\\}\\)`",
        "2. 欠損（部分観測）: `\\(z_i\\)` が観測できない成分",
        "3. 座標（連続）: `\\(z_i\\in\\mathbb{R}^m\\)` が低次元表現",
        "",
        "同じ `\\(\\int\\)` でも、離散なら和、連続なら積分。ここは最初に固定しておく。",
        "",
        "```math",
        "\\int p(x,z)dz",
        "\\quad\\text{は}\\quad",
        "\\sum_{z} p(x,z) \\ \\text{（離散）},",
        "\\qquad",
        "\\int_{\\mathbb{R}^m} p(x,z)\\,dz \\ \\text{（連続）}",
        "```",
        "",
        "次に、下界への一本道へ入る。",
        "",
        "---",
        "",
        "## ⚔️ Z4. Boss Battle（60分）",
        "",
        "### 4.1 まずは目的関数を正確に書く",
        "",
        "データ `\\(\\mathcal{D}=\\{x_i\\}_{i=1}^N\\)` に対し、周辺尤度（不完全データ尤度）を最大化したい。",
        "",
        "```math",
        "\\mathcal{L}(\\theta)",
        "= \\sum_{i=1}^N \\log p_\\theta(x_i)",
        "= \\sum_{i=1}^N \\log \\int p_\\theta(x_i,z_i)\\,dz_i",
        "```",
        "",
        "ここで詰まる理由は、単に積分が難しいからではない。",
        "",
        "- `\\(\\log\\int\\)` の形は、微分しても閉じない",
        "- `\\(z\\)` が高次元だと、積分は指数的に爆発する",
        "",
        "だから、直接 `\\(\\mathcal{L}(\\theta)\\)` を最大化しない。",
        "",
        "### 4.2 Jensen不等式: 「ログの中身」を平均にする",
        "",
        "鍵は、`\\(\\log\\)` の前に「期待値」を置くこと。",
        "",
        "```math",
        "\\log \\mathbb{E}[Y] \\ge \\mathbb{E}[\\log Y]",
        "\\qquad (\\log\\ \\text{は凹関数})",
        "```",
        "",
        "ただし今は、`\\(\\mathbb{E}\\)` を持っていない。そこで、補助分布 `\\(q(z)\\)` を自分で入れる。",
        "",
        "```math",
        "p_\\theta(x)=\\int p_\\theta(x,z)\\,dz",
        "=\\int q(z)\\,\\frac{p_\\theta(x,z)}{q(z)}\\,dz",
        "=\\mathbb{E}_{q(z)}\\Bigl[\\frac{p_\\theta(x,z)}{q(z)}\\Bigr]",
        "```",
        "",
        "この時点で Jensen が刺さる。",
        "",
        "```math",
        "\\log p_\\theta(x)",
        "= \\log \\mathbb{E}_{q(z)}\\Bigl[\\frac{p_\\theta(x,z)}{q(z)}\\Bigr]",
        "\\ge \\mathbb{E}_{q(z)}\\Bigl[\\log p_\\theta(x,z) - \\log q(z)\\Bigr]",
        "```",
        "",
        "右辺が ELBO（Evidence Lower Bound）。",
        "",
        "### 4.3 ELBO 分解: ギャップは KL",
        "",
        "ここで「なぜ EM が収束っぽい動きをするか」が見える形になる。",
        "",
        "```math",
        "\\log p_\\theta(x) = \\mathrm{ELBO}(q,\\theta) + D_{\\mathrm{KL}}\\bigl(q(z)\\|p_\\theta(z\\mid x)\\bigr)",
        "```",
        "",
        "この等式は、次の事実を同時に言っている。",
        "",
        "- `\\(D_{\\mathrm{KL}}\\ge 0\\)` だから `\\(\\mathrm{ELBO}\\le \\log p_\\theta(x)\\)`（下界）",
        "- ギャップは `\\(q(z)=p_\\theta(z\\mid x)\\)` のときに 0",
        "",
        "*mermaid: 分解の見取り図*",
        "",
    ]
    L += mermaid_elbo_decomp()
    L += [
        "",
        "### 4.4 EM を「交互最適化」として導く",
        "",
        "狙いは `\\(\\log p_\\theta(x)\\)` を上げること。だが直接は無理なので、下界 `\\(\\mathrm{ELBO}(q,\\theta)\\)` を上げる。",
        "",
        "EM は次の2つを交互に行う。",
        "",
        "```math",
        "\\textbf{E-step:}\\quad q^{(t+1)}(z) := \\arg\\max_q \\mathrm{ELBO}(q,\\theta^{(t)})",
        "```",
        "",
        "```math",
        "\\textbf{M-step:}\\quad \\theta^{(t+1)} := \\arg\\max_\\theta \\mathrm{ELBO}(q^{(t+1)},\\theta)",
        "```",
        "",
        "E-step は `\\(q(z)=p_{\\theta^{(t)}}(z\\mid x)\\)` が最適。",
        "",
        "理由: `\\(\\mathrm{ELBO}=\\log p_\\theta(x)-D_{\\mathrm{KL}}(q\\|p_\\theta)\\)` だから、`\\(q\\)` を動かすと KL を最小化する問題に落ちる。",
        "",
        "### 4.5 単調増加の骨格（なぜ loglik が落ちないか）",
        "",
        "EM の肝は「`\\(\\log p_\\theta(x)\\)` が反復で下がらない」という単調性。",
        "",
        "ここは式変形の順序がすべて。",
        "",
        "1. E-step で `\\(q\\)` を最適化して ELBO を上げる（もしくはギャップを消す）",
        "2. M-step で `\\(\\theta\\)` を最適化して ELBO を上げる",
        "3. `\\(\\log p_\\theta(x)\\)` は ELBO 以上なので、結果として `\\(\\log p\\)` も上がる",
        "",
        "*mermaid: EM反復*",
        "",
    ]
    L += mermaid_em_flow()
    L += [
        "",
        "### 4.6 具体例: GMM（Gaussian Mixture Model）",
        "",
        "#### 4.6.1 モデル",
        "",
        "観測 `\\(x\\in\\mathbb{R}^d\\)`、成分 `\\(k\\in\\{1,\\dots,K\\}\\)`。",
        "",
        "```math",
        "p_\\theta(x) = \\sum_{k=1}^K \\pi_k\\,\\mathcal{N}(x\\mid\\mu_k,\\Sigma_k)",
        "\\quad",
        "\\sum_k \\pi_k=1,\\ \\pi_k\\ge 0",
        "```",
        "",
        "潜在変数 `\\(z\\)` を one-hot `\\(z\\in\\{e_1,\\dots,e_K\\}\\)` として書くと、完全データ尤度が綺麗になる。",
        "",
        "```math",
        "p_\\theta(x,z)",
        "=\\prod_{k=1}^K \\Bigl(\\pi_k\\,\\mathcal{N}(x\\mid\\mu_k,\\Sigma_k)\\Bigr)^{z_k}",
        "```",
        "",
        "この形は「ログを取ると和になる」ので、M-step が閉じる。",
        "",
        "#### 4.6.2 完全データ対数尤度",
        "",
        "```math",
        "\\log p_\\theta(x,z)",
        "=\\sum_{k=1}^K z_k\\Bigl(\\log \\pi_k + \\log \\mathcal{N}(x\\mid\\mu_k,\\Sigma_k)\\Bigr)",
        "```",
        "",
        "#### 4.6.3 Q関数",
        "",
        "```math",
        "Q(\\theta\\mid\\theta^{(t)})",
        ":=\\mathbb{E}_{z\\sim p(z\\mid x,\\theta^{(t)})}[\\log p_\\theta(x,z)]",
        "```",
        "",
        "GMM では `\\(\\mathbb{E}[z_k]=\\gamma_k\\)` が責任度（responsibility）。",
        "",
        "#### 4.6.4 E-step: 責任度",
        "",
        "```math",
        "\\gamma_{ik}:=p(z_i=k\\mid x_i,\\theta^{(t)})",
        "=\\frac{\\pi_k\\,\\mathcal{N}(x_i\\mid\\mu_k,\\Sigma_k)}{\\sum_{j=1}^K \\pi_j\\,\\mathcal{N}(x_i\\mid\\mu_j,\\Sigma_j)}",
        "```",
        "",
        "ここで必ず確認する性質が2つある。",
        "",
        "- `\\(\\gamma_{ik}\\ge 0\\)`（確率）",
        "- `\\(\\sum_k \\gamma_{ik}=1\\)`（正規化）",
        "",
        "#### 4.6.5 M-step: 更新式",
        "",
        "```math",
        "N_k:=\\sum_{i=1}^N \\gamma_{ik}",
        "\\quad",
        "\\pi_k\\leftarrow \\frac{N_k}{N}",
        "\\quad",
        "\\mu_k\\leftarrow \\frac{1}{N_k}\\sum_i \\gamma_{ik}x_i,",
        "\\quad",
        "\\Sigma_k\\leftarrow \\frac{1}{N_k}\\sum_i \\gamma_{ik}(x_i-\\mu_k)(x_i-\\mu_k)^\\top",
        "```",
        "",
        "式そのものは「重み付き平均」「重み付き分散」。難しいのは shape を落とさず実装に落とすこと。",
        "",
        "#### 4.6.6 shape を固定する（落とすと死ぬ）",
        "",
        "- `\\(x_i\\in\\mathbb{R}^d\\)`",
        "- `\\(\\mu_k\\in\\mathbb{R}^d\\)`",
        "- `\\(\\Sigma_k\\in\\mathbb{R}^{d\\times d}\\)`",
        "- `\\(\\gamma\\in\\mathbb{R}^{N\\times K}\\)`（行がデータ、列が成分）",
        "",
        "この追跡が崩れると、(a) 転置のし忘れ、(b) ブロードキャストの誤用、(c) 共分散が対称でなくなる、が連鎖して破綻する。",
        "",
        "*mermaid: GMMの生成の見取り図*",
        "",
    ]
    L += mermaid_gmm_components()
    L += [
        "",
        "### 4.7 EMの拡張",
        "",
        "#### 4.7.1 Generalized EM（GEM）",
        "",
        "M-step を厳密最大化できないなら、少なくとも `\\(Q\\)` を増やす方向に進めばよい。",
        "",
        "```math",
        "Q(\\theta^{(t+1)}\\mid\\theta^{(t)}) \\ge Q(\\theta^{(t)}\\mid\\theta^{(t)})",
        "```",
        "",
        "#### 4.7.2 ECM（条件付き最大化）",
        "",
        "`\\(\\theta=(\\theta_1,\\theta_2,\\dots)\\)` をブロックに分けて順番に最大化する。",
        "",
        "#### 4.7.3 label switching（同一性）",
        "",
        "GMM の成分ラベルは入れ替えても同じ分布を表す。",
        "",
        "```math",
        "(\\pi_1,\\mu_1,\\Sigma_1),\\dots,(\\pi_K,\\mu_K,\\Sigma_K)",
        "\\quad\\text{は}\\quad",
        "k\\text{を置換しても同じ }p_\\theta(x)",
        "```",
        "",
        "だから「学習がうまくいった」の判定は、ラベル一致ではなく尤度やクラスタの形で見る必要がある。",
        "",
        "#### 4.7.4 singularity（尤度の発散）",
        "",
        "GMM の MLE は、ある成分の共分散を 0 に潰して一点に過適合すると尤度が発散する（無限大へ飛ぶ）。",
        "",
        "この現象は、実装ではこう見える。",
        "",
        "- `\\(\\Sigma_k\\)` が特異（行列式が 0 に近い）になり、Cholesky 分解が失敗する",
        "- `\\(\\gamma\\)` がほぼ one-hot になり、`\\(N_k\\)` が極端に小さい成分が出る",
        "",
        "対策は Part2 で実務的にまとめる。",
        "",
        "### 4.8 欠損データと潜在変数",
        "",
        "潜在変数が「未観測」なら、欠損のメカニズムを区別する必要がある。",
        "",
        "- MCAR: Missing Completely At Random",
        "- MAR: Missing At Random",
        "- MNAR: Missing Not At Random",
        "",
        "ここは詳細に踏み込みすぎない。ただし EM の適用可否はこの区別で決まる。",
        "",
        "---",
        "",
        "## 付録A: Jensen→ELBO を『行単位』で追う（導出台帳）",
        "",
        "この付録は、暗記ではなく「順番」を固定するためのノート。",
        "",
        "```math",
        "\\log p_\\theta(x)",
        "= \\log \\int p_\\theta(x,z)\\,dz",
        "= \\log \\int q(z)\\,\\frac{p_\\theta(x,z)}{q(z)}\\,dz",
        "= \\log \\mathbb{E}_{q(z)}\\Bigl[\\frac{p_\\theta(x,z)}{q(z)}\\Bigr]",
        "\\ge \\mathbb{E}_{q(z)}[\\log p_\\theta(x,z)-\\log q(z)]",
        "```",
        "",
        "落とし穴（数学として破綻するもの）:",
        "",
        "- `q(z)` は確率分布（非負・積分1）でなければならない",
        "- `q(z)=0` で `p(x,z)>0` があると `p/q` が壊れる（support 条件）",
        "",
        "```math",
        "q(z)=0 \\Rightarrow p_\\theta(x,z)=0",
        "```",
        "",
        "ELBO 分解の核になる恒等式:",
        "",
        "```math",
        "D_{\\mathrm{KL}}\\bigl(q(z)\\|p_\\theta(z\\mid x)\\bigr)",
        "=\\mathbb{E}_q[\\log q(z)]-\\mathbb{E}_q[\\log p_\\theta(x,z)]+\\log p_\\theta(x)",
        "```",
        "",
        "この式を `\\(\\log p_\\theta(x)\\)` について解けば分解が出る。",
        "",
        "---",
        "",
        "## 付録B: 多変量ガウスの log 密度を分解して持つ",
        "",
        "GMM の実装で壊れるのは、ほぼここ（`logdet` と 二次形式）。",
        "",
        "```math",
        "\\log \\mathcal{N}(x\\mid\\mu,\\Sigma)",
        "=-\\frac{1}{2}\\Bigl(d\\log(2\\pi)+\\log\\det\\Sigma+(x-\\mu)^\\top\\Sigma^{-1}(x-\\mu)\\Bigr)",
        "```",
        "",
        "Cholesky で書き直す（`\\Sigma^{-1}` を直接作らない）:",
        "",
        "```math",
        "\\Sigma = LL^\\top,\\quad",
        "(x-\\mu)^\\top\\Sigma^{-1}(x-\\mu)=\\|L^{-1}(x-\\mu)\\|_2^2,\\quad",
        "\\log\\det\\Sigma = 2\\sum_{j=1}^d \\log L_{jj}",
        "```",
        "",
        "---",
        "",
        "## 付録C: M-step をラグランジュ未定乗数で閉じる（混合比 π）",
        "",
        "混合比は制約 `\\(\\sum_k\\pi_k=1\\)` を持つ。更新式は制約付き最適化の帰結。",
        "",
        "```math",
        "\\max_{\\pi}\\ \\sum_{i,k}\\gamma_{ik}\\log\\pi_k",
        "\\quad\\text{s.t.}\\quad \\sum_k \\pi_k=1",
        "```",
        "",
        "```math",
        "\\mathcal{J}(\\pi,\\lambda)=\\sum_k N_k\\log\\pi_k + \\lambda\\Bigl(\\sum_k\\pi_k-1\\Bigr)",
        "\\Rightarrow",
        "\\pi_k=\\frac{N_k}{N}",
        "```",
        "",
        "---",
        "",
        "## 付録D: EM と変分推論（次回への接続）",
        "",
        "E-step が閉じない（`p(z|x,θ)` が計算不能）なら、`q(z)` を制約付きで最適化する方向へ進む。",
        "",
        "```math",
        "q(z)\\in\\mathcal{Q} \\quad\\Rightarrow\\quad \\max_{q\\in\\mathcal{Q}}\\mathrm{ELBO}(q,\\theta)",
        "```",
        "",
        "これが Variational EM。VAE は `q` を推論ネットで直接出して amortize する。",
    ]

    L += [
        "",
        "---",
        "",
        "## 参考文献",
        "",
        "[^1]: <https://arxiv.org/abs/0710.5696>",
        "[^2]: <https://arxiv.org/abs/cs/0412015>",
        "[^3]: <https://arxiv.org/abs/1105.1476>",
        "[^4]: <https://arxiv.org/abs/0712.4273>",
        "[^5]: <https://arxiv.org/abs/1601.00670>",
        "",
    ]
    L += author_links_and_license()
    return L


def build_part2() -> list[str]:
    L: list[str] = []
    L += frontmatter_part2()

    L += [
        "> **この講義について**",
        "> Part1 の導出を、そのまま手で動かす。ここから先は「式が動く」ことだけを狙う。",
        ">",
        "> **前編はこちら**: [第8回 Part1（理論編）](/articles/ml-lecture-08-part1)",
        "",
        "## Learning Objectives",
        "",
        "- [ ] 責任度 `\\(\\gamma_{ik}\\)` を log-sum-exp で安定に計算できる",
        "- [ ] 多変量 GMM の M-step を shape つきで実装できる",
        "- [ ] BIC/AIC を使ったモデル選択を式から実装へ落とせる",
        "- [ ] singularity と label switching を「起き方」から説明できる",
        "",
        "---",
        "",
        "## 🛠️ Z5. 実装ゾーン（60分）",
        "",
        "### 5.0 実装の設計図（最初に壊れる場所を潰す）",
        "",
        "GMM-EM で壊れる場所はだいたい4つに集約する。",
        "",
        "- `\\(\\gamma\\)` の正規化が崩れる（和が 1 にならない）",
        "- `\\(\\Sigma\\)` が SPD（正定値）でなくなる（Cholesky が落ちる）",
        "- 対数尤度の計算が underflow/overflow する（`log(0)`、`exp(1000)`）",
        "- 初期化が悪く局所解に落ちる（クラスタが潰れる）",
        "",
        "ここでは、式と変数名を一致させる。",
        "",
        "- 記号 `\\(\\pi,\\mu,\\Sigma,\\gamma\\)` → 変数 `pi, mu, Sigma, gamma`",
        "- `\\(N\\)`（データ数）, `\\(K\\)`（成分数）, `\\(d\\)`（次元）",
        "",
        "*mermaid: 系譜図*",
        "",
    ]
    L += mermaid_lineage()
    L += [
        "",
        "### 5.1 数値安定性: log-sum-exp で責任度を作る",
        "",
        "計算したいのは `\\(\\gamma_{ik}\\)` だが、直接 `\\(\\pi_k\\mathcal{N}(x_i|\\mu_k,\\Sigma_k)\\)` を作ると `0` に潰れる。",
        "",
        "そこで log 空間に上げて、正規化だけは `log-sum-exp` でやる。",
        "",
        "shape（責任度計算の中で最低限見る形）:",
        "",
        "- `X \\in \\mathbb{R}^{N\\times d}`",
        "- `pi \\in \\mathbb{R}^{K}`",
        "- `mu \\in \\mathbb{R}^{K\\times d}`",
        "- `Sigma \\in \\mathbb{R}^{K\\times d\\times d}`",
        "- `gamma \\in \\mathbb{R}^{N\\times K}`",
        "",
        "記号↔変数名:",
        "",
        "- `\\(\\pi_k\\)` ↔ `pi[k]`",
        "- `\\(\\mu_k\\)` ↔ `mu[k]`",
        "- `\\(\\Sigma_k\\)` ↔ `Sigma[k]`",
        "- `\\(\\gamma_{ik}\\)` ↔ `gamma[i, k]`",
        "",
        "落とし穴（最低限）:",
        "",
        "- `logsumexp` は `max` を引いてから `exp` する",
        "- `\\(\\Sigma_k\\)` は `eps I` を足して SPD に寄せる",
        "",
        "検算（必須）:",
        "",
        "- `gamma.sum(axis=1)` の min/max が 1 に張り付くこと",
        "",
        "```math",
        "\\log\\sum_{k=1}^K e^{a_k} = m + \\log\\sum_{k=1}^K e^{a_k-m},\\quad m=\\max_k a_k",
        "```",
        "",
        "```python",
        "import numpy as np",
        "",
        "",
        "def logsumexp(a, axis=-1):",
        "    m = np.max(a, axis=axis, keepdims=True)",
        "    s = np.sum(np.exp(a - m), axis=axis, keepdims=True)",
        "    return (m + np.log(s)).squeeze(axis)",
        "",
        "",
        "# sanity: overflow-safe",
        "z = np.array([1000.0, 999.0, 998.0])",
        "print(\"naive exp finite? ->\", np.isfinite(np.sum(np.exp(z))))",
        "print(\"logsumexp        ->\", float(logsumexp(z)))",
        "```",
        "",
        "### 5.2 M-step: 更新式をそのまま実装する",
        "",
        "E-step ができたら、残りは重み付き統計量。",
        "",
        "```math",
        "N_k = \\sum_{i=1}^N \\gamma_{ik},\\quad",
        "\\pi_k = \\frac{N_k}{N},\\quad",
        "\\mu_k = \\frac{1}{N_k}\\sum_{i=1}^N \\gamma_{ik}x_i,\\quad",
        "\\Sigma_k = \\frac{1}{N_k}\\sum_{i=1}^N \\gamma_{ik}(x_i-\\mu_k)(x_i-\\mu_k)^\\top",
        "```",
        "",
        "shape の落とし穴は `\\(\\Sigma_k\\)` だけ。",
        "",
        "- `(x_i-\\mu_k)(x_i-\\mu_k)^T` は `d×d`",
        "- `\\gamma_{ik}` はスカラー重み",
        "- 総和は `i` に対して回す",
        "",
        "数値安定化の最小手当:",
        "",
        "- `Sigma[k] = (Sigma[k] + Sigma[k].T) / 2`（対称化）",
        "- `Sigma[k] += eps I`（SPDへの寄せ）",
        "",
        "検算（最低1つ）:",
        "",
        "- `np.all(np.linalg.eigvalsh(Sigma[k]) > 0)` を（小さな eps つきで）確認する",
        "",
        "```math",
        "\\log \\gamma_{ik}",
        "= \\log \\pi_k + \\log \\mathcal{N}(x_i\\mid\\mu_k,\\Sigma_k)",
        "- \\log\\sum_{j=1}^K \\exp\\Bigl(\\log \\pi_j + \\log \\mathcal{N}(x_i\\mid\\mu_j,\\Sigma_j)\\Bigr)",
        "",
        "N_k = \\sum_{i=1}^N \\gamma_{ik},\\quad",
        "\\pi_k = \\frac{N_k}{N},\\quad",
        "\\mu_k = \\frac{1}{N_k}\\sum_{i=1}^N \\gamma_{ik}x_i,\\quad",
        "\\Sigma_k = \\frac{1}{N_k}\\sum_{i=1}^N \\gamma_{ik}(x_i-\\mu_k)(x_i-\\mu_k)^\\top",
        "",
        "\\mathrm{AIC}=2\\,k_{\\mathrm{params}}-2\\,\\log p(X\\mid\\hat\\theta),",
        "\\qquad",
        "\\mathrm{BIC}=\\log(N)\\,k_{\\mathrm{params}}-2\\,\\log p(X\\mid\\hat\\theta)",
        "```",
        "",
        "```python",
        "import numpy as np",
        "",
        "",
        "def logsumexp(a, axis=-1):",
        "    m = np.max(a, axis=axis, keepdims=True)",
        "    s = np.sum(np.exp(a - m), axis=axis, keepdims=True)",
        "    return (m + np.log(s)).squeeze(axis)",
        "",
        "",
        "def log_mvnormal(X, mu_k, Sigma_k, eps=1e-6):",
        "    # X: (N,d), mu_k: (d,), Sigma_k: (d,d)",
        "    N, d = X.shape",
        "    Sigma_k = Sigma_k + eps * np.eye(d)",
        "    L = np.linalg.cholesky(Sigma_k)",
        "    Y = np.linalg.solve(L, (X - mu_k).T)  # (d,N)",
        "    quad = np.sum(Y * Y, axis=0)          # (N,)",
        "    logdet = 2.0 * np.sum(np.log(np.diag(L)))",
        "    return -0.5 * (d * np.log(2.0 * np.pi) + logdet + quad)",
        "",
        "",
        "def e_step(X, pi, mu, Sigma):",
        "    N = X.shape[0]",
        "    K = pi.shape[0]",
        "    log_r = np.zeros((N, K))",
        "    for k in range(K):",
        "        log_r[:, k] = np.log(pi[k] + 1e-12) + log_mvnormal(X, mu[k], Sigma[k])",
        "",
        "    log_norm = logsumexp(log_r, axis=1)      # (N,)",
        "    gamma = np.exp(log_r - log_norm[:, None])",
        "",
        "    row_sum = gamma.sum(axis=1)",
        "    print(\"gamma row-sum min/max:\", float(row_sum.min()), float(row_sum.max()))",
        "    return gamma",
        "",
        "",
        "def m_step(X, gamma, eps=1e-6):",
        "    # X: (N,d), gamma: (N,K)",
        "    N, d = X.shape",
        "    K = gamma.shape[1]",
        "",
        "    Nk = gamma.sum(axis=0) + 1e-12          # (K,)",
        "    pi = Nk / float(N)                      # (K,)",
        "    mu = (gamma.T @ X) / Nk[:, None]        # (K,d)",
        "",
        "    Sigma = np.zeros((K, d, d))",
        "    for k in range(K):",
        "        Xc = X - mu[k][None, :]             # (N,d)",
        "        Sigma[k] = (gamma[:, k][:, None] * Xc).T @ Xc / Nk[k]",
        "        Sigma[k] = 0.5 * (Sigma[k] + Sigma[k].T)",
        "        Sigma[k] = Sigma[k] + eps * np.eye(d)",
        "",
        "    # sanity: SPD-ish",
        "    for k in range(K):",
        "        lam_min = float(np.linalg.eigvalsh(Sigma[k]).min())",
        "        print(f\"Sigma[{k}] min-eig: {lam_min:.3e}\")",
        "",
        "    return pi, mu, Sigma",
        "",
        "",
        "def loglik_gmm(X, pi, mu, Sigma):",
        "    N = X.shape[0]",
        "    K = pi.shape[0]",
        "    log_r = np.zeros((N, K))",
        "    for k in range(K):",
        "        log_r[:, k] = np.log(pi[k] + 1e-12) + log_mvnormal(X, mu[k], Sigma[k])",
        "    return float(np.sum(logsumexp(log_r, axis=1)))",
        "",
        "",
        "def run_em(X, K, steps=30, seed=0):",
        "    rng = np.random.default_rng(seed)",
        "    N, d = X.shape",
        "",
        "    # simple init: random subset for means, shared covariance",
        "    idx = rng.choice(N, size=K, replace=False)",
        "    mu = X[idx].copy()                      # (K,d)",
        "    pi = np.ones(K) / K                     # (K,)",
        "    Sigma0 = np.cov(X.T) + 1e-3 * np.eye(d)  # (d,d)",
        "    Sigma = np.stack([Sigma0.copy() for _ in range(K)], axis=0)",
        "",
        "    ll_hist = []",
        "    for t in range(steps):",
        "        gamma = e_step(X, pi, mu, Sigma)",
        "        pi, mu, Sigma = m_step(X, gamma)",
        "        ll = loglik_gmm(X, pi, mu, Sigma)",
        "        ll_hist.append(ll)",
        "        if t >= 1:",
        "            assert ll_hist[-1] >= ll_hist[-2] - 1e-6  # monotonicity (numerical slack)",
        "",
        "    return pi, mu, Sigma, np.array(ll_hist)",
        "",
        "",
        "def aic_bic(loglik, N, k_params):",
        "    aic = 2.0 * k_params - 2.0 * loglik",
        "    bic = np.log(float(N)) * k_params - 2.0 * loglik",
        "    return aic, bic",
        "",
        "",
        "# demo: synthetic 2D mixture",
        "rng = np.random.default_rng(0)",
        "X = np.vstack([",
        "    rng.normal(loc=(-2.0, 0.0), scale=0.6, size=(200, 2)),",
        "    rng.normal(loc=(+2.0, 0.0), scale=0.6, size=(200, 2)),",
        "])",
        "",
        "for K in [1, 2, 3, 4]:",
        "    pi, mu, Sigma, ll_hist = run_em(X, K, steps=20, seed=K)",
        "    ll = float(ll_hist[-1])",
        "",
        "    # parameter count (full covariance): (K-1) + K*d + K*d*(d+1)/2",
        "    N, d = X.shape",
        "    k_params = (K - 1) + K * d + K * (d * (d + 1) // 2)",
        "    aic, bic = aic_bic(ll, N, k_params)",
        "    print(\"K=\", K, \"loglik=\", ll, \"AIC=\", aic, \"BIC=\", bic)",
        "```",
        "",
        "> **Note:** `assert` が落ちるときは、式が間違いというより数値不安定（eps不足、SPD崩壊、初期化）を疑う。",
        "",
        "### 5.3 初期化（K-means++ をどう使うか）",
        "",
        "実装で一番効くのは初期値。`\\(\\mu_k\\)` を良い位置に置ければ、EM はその周りで整う。",
        "",
        "- 最低限: `\\(\\mu\\)` をデータからランダム抽出（上の実装）",
        "- もっと良い: `\\(\\mu\\)` を K-means++ 的に分散させる",
        "- さらに: 1-2回だけ K-means を回してから EM へ渡す",
        "",
        "ここはコードを増やすより、何が起きるかを言える方が重要。",
        "",
        "### 5.4 singularity と対策（実務版）",
        "",
        "現場で起きる典型症状。",
        "",
        "- `Sigma[k]` の最小固有値が負になる",
        "- `Nk[k]` が 1 未満まで落ちる（ほぼ空クラスタ）",
        "- `loglik` が突然跳ね上がる（一点への過適合）",
        "",
        "対策は、強さ順にこう。",
        "",
        "1. `Sigma[k] += eps I`（最小手当）",
        "2. `Nk[k]` が小さい成分を再初期化（`mu[k]` をデータから引き直す）",
        "3. 事前分布を入れる（MAP-EM: Wishart/Dirichlet）",
        "",
        "*mermaid: 数値安定性の流れ*",
        "",
        "```mermaid",
        "flowchart TD",
        "  A[raw density π_k N(x|μ_k,Σ_k)] --> B[underflow to 0]",
        "  B --> C[log space: log π_k + log N]",
        "  C --> D[normalize with log-sum-exp]",
        "  D --> E[exp back to γ]",
        "  E --> F[assert row-sum == 1]",
        "```",
        "",
        "*mermaid: モデル選択（AIC/BIC）*",
        "",
        "```mermaid",
        "flowchart LR",
        "  D[data X] --> F[fit EM for each K]",
        "  F --> L[loglik(K)]",
        "  L --> A[AIC(K)]",
        "  L --> B[BIC(K)]",
        "  A --> S[select K (tradeoff)]",
        "  B --> S",
        "```",
        "",
        "*mermaid: singularity の発火パターン*",
        "",
        "```mermaid",
        "flowchart TD",
        "  A[component collapses] --> B[Σ_k shrinks]",
        "  B --> C[det(Σ_k) -> 0]",
        "  C --> D[log N(x|μ,Σ) -> +∞ at a point]",
        "  D --> E[loglik spikes, Cholesky fails]",
        "  E --> F[fix: epsI / reinit / priors]",
        "```",
        "",
        "*mermaid: ループとベクトル化の境目*",
        "",
        "```mermaid",
        "flowchart LR",
        "  A[for-loop over i,k] -->|slow| B[vectorize log_r]",
        "  B --> C[still need Cholesky per k]",
        "  C --> D[hotspots: (K times) solve/triangular]",
        "  D --> E[profile -> move heavy parts to faster stack]",
        "```",
        "",
        "---",
        "",
        "## 🔬 Z6. EM の子孫たち（20分）",
        "",
        "EM が出てくるのは「潜在があるが、事後が閉じない」問題全般。",
        "",
        "- HMM: 事後が時系列の依存を持つ（Baum-Welch）[^2]",
        "- PPCA: 線形ガウスの潜在（閉じるが EM で整理すると見通しが良い）",
        "- Variational EM: 事後を `q(z)` で近似する（VAE へ直結）[^5]",
        "- EP: 近似の別系統（局所近似の積で全体を作る）[^6]",
        "",
        "---",
        "",
        "## 🎓 Z7. Course I フィナーレ（10分）",
        "",
        "8回で手に入ったものは、単に道具ではない。式を読む筋力が増えた。",
        "",
        "- 線形代数: shape を落とさない視点",
        "- 解析: 近似と収束の言語",
        "- 確率・測度: `\\(\\int\\)` の正体",
        "- 情報理論: KL と下界という羅針盤",
        "- EM: 下界を押し上げる反復（潜在の扱い方）",
        "",
        "次は変分推論。`q(z)` を「最適に選ぶ」から「学習で作る」へ進む。",
        "",
    ]

    L += [
        "",
        "## 付録: 実装を壊さないためのデバッグ観測点",
        "",
        "短い実装ほど、壊れたときに原因が見えにくい。だから観測点を固定する。",
        "",
        "### 観測点1: `gamma` の行和",
        "",
        "- 期待: `gamma.sum(axis=1)` が 1 に張り付く",
        "- 崩れたら: `logsumexp` の軸、`keepdims`、`exp(log_r - log_norm[:,None])` の引き算方向を疑う",
        "",
        "### 観測点2: `Sigma[k]` のSPD性",
        "",
        "- 期待: `min_eig(Sigma[k]) > 0`（`eps` 分だけ正）",
        "- 崩れたら: empty component / 対称化不足 / `eps I` 不足",
        "",
        "### 観測点3: loglik の単調性",
        "",
        "- 期待: `ll[t] >= ll[t-1] - 1e-6`",
        "- 崩れたら: `Sigma` がギリギリ / `gamma` の正規化崩れ / empty component",
        "",
        "### 観測点4: `Nk`",
        "",
        "- 期待: `Nk` が小さい成分を検出して対処する",
        "- 対処: 再初期化、`pi` クリップ、MAP-EM（事前分布）",
        "",
        "---",
        "",
        "## 付録: パラメータ数 `k_params` の数え方（BIC/AIC）",
        "",
        "full covariance の多変量GMM（`d` 次元、`K` 成分）での自由パラメータ数は次の合計。",
        "",
        "- 混合比 `π`: `K` 個だが和1制約で `K-1`",
        "- 平均 `μ`: `K*d`",
        "- 共分散 `Σ`: 対称行列なので `d(d+1)/2` が1成分、合計 `K*d(d+1)/2`",
        "",
        "```math",
        "k_{\\mathrm{params}}=(K-1)+K\\,d + K\\,\\frac{d(d+1)}{2}",
        "```",
        "",
        "この数え方を間違えるとモデル選択が壊れる（`K` を増やすほど有利になる等）。",
        "",
        "---",
        "",
        "## 参考文献",
        "",
        "[^1]: <https://arxiv.org/abs/0710.5696>",
        "[^2]: <https://arxiv.org/abs/cs/0412015>",
        "[^3]: <https://arxiv.org/abs/1105.1476>",
        "[^4]: <https://arxiv.org/abs/0712.4273>",
        "[^5]: <https://arxiv.org/abs/1601.00670>",
        "[^6]: <https://arxiv.org/abs/1301.2294>",
        "",
    ]
    L += author_links_and_license()
    return L


def main() -> None:
    part1 = ARTICLES / "ml-lecture-08-part1.md"
    part2 = ARTICLES / "ml-lecture-08-part2.md"
    write_lines(part1, build_part1())
    write_lines(part2, build_part2())


if __name__ == "__main__":
    main()
